package uk.co.gencoreoperative.runner;

import static uk.co.gencoreoperative.runner.ModelType.*;

import java.io.IOException;
import java.nio.file.Path;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.annotation.Nonnull;

import mukel.qwen2.Qwen2;
import uk.co.gencoreoperative.Config;
import uk.co.gencoreoperative.ai.ContextWindow;
import uk.co.gencoreoperative.ai.Response;
import uk.co.gencoreoperative.ai.Run;
import uk.co.gencoreoperative.utils.BlockingQueueIterator;
import uk.co.gencoreoperative.utils.QueuingOutputStream;
import uk.co.gencoreoperative.utils.RunAsync;
import mukel.llama3.Llama3;

/**
 * Based on the excellent work by <a href="https://github.com/mukel/llama3.java>mukel</a>,
 * this class runs the Llama3 model with the provided prompt.
 * <p>
 * The code provided was intended for use on the command line. This class adapts this by
 * capturing the output of the model and returning it as a string.
 * <p>
 * The Llama3.java library we are using is best invoked using its {@link Llama3#main(String[])}
 * method. This call will generate stdout and stderr that will be re-diverted to simplify the
 * experience for the caller. From the caller's perspective, we are only interested in the output
 * of the model.
 */
public class MukelRunner implements Run {
    private final Path modelPath;
    private final ModelType modelType;

    public MukelRunner(Path modelPath) {
        modelType = validateModelPath(modelPath);
        this.modelPath = modelPath;
    }

    /**
     * @return The name of the model provided to this runner.
     */
    public String getModelName() {
        return modelType.name();
    }

    /**
     * Validate the provided LLM model to ensure it is likely to be runnable by {@link Qwen2} or {@link Llama3}.
     * @param modelPath The {@link Path} to the model.
     * @return The {@link ModelType} of the model based on the path.
     */
    private @Nonnull ModelType validateModelPath(@Nonnull Path modelPath) {
        String lowerCaseName = modelPath.getFileName().toString().toLowerCase();
        if (!lowerCaseName.contains("q4_0")) throw new IllegalArgumentException("Model must be a Q4_0 model");
        if (!lowerCaseName.endsWith(".gguf")) throw new IllegalArgumentException("Model must be a .gguf file");

        if (lowerCaseName.contains(QWEN2.getSearchString())) {
            return QWEN2;
        } else if (lowerCaseName.contains(LLAMA3.getSearchString())) {
            return LLAMA3;
        } else {
            throw new IllegalArgumentException("Model must be a Qwen2 or Llama3 model");
        }
    }

    /**
     * Perform a single AI request with the provided configuration options and return a {@link Response} object.
     * <p>
     * This method provides detailed information about the LLM invocation, including output, context window, and duration.
     *
     * @param options The {@link Config} object containing the system prompt, user prompt, temperature, and other settings.
     * @return A {@link Response} object containing the model's output, context window, and metadata.
     * @throws RuntimeException if the model invocation fails or an error occurs during processing.
     */
    @Override
    public Response runWithResponse(@Nonnull Config options) throws RuntimeException {

        BlockingQueueIterator output = new BlockingQueueIterator();
        BlockingQueueIterator error = new BlockingQueueIterator();
        String[] args = buildArgs(options);

        long start = System.currentTimeMillis();
        getInvoker(args, output, error).run();
        Duration duration = Duration.of(System.currentTimeMillis() - start, ChronoUnit.MILLIS);

        String completeError = BlockingQueueIterator.createStream(error).collect(Collectors.joining());
        String completeOutput = BlockingQueueIterator.createStream(output).collect(Collectors.joining());

        return new Response(completeOutput, ContextWindow.parse(completeError), duration);
    }

/**
 * Perform a single request and wait for the complete response from the LLM before returning.
 *
 * @param options The {@link Config} object containing the system prompt, user prompt, and other settings.
 * @return The output of the model if any.
 */
    public String run(@Nonnull Config options) {
        BlockingQueueIterator output = new BlockingQueueIterator();
        BlockingQueueIterator error = new BlockingQueueIterator();
        String[] args = buildArgs(options);
        RunAsync.runAsync(getInvoker(args, output, error));
        return BlockingQueueIterator.createStream(output).collect(Collectors.joining());
    }


    /**
     * Invoke the LLM to perform a request and return immediately to the caller.
     * <p>
     * This method will run asynchronously and will stream the characters generated by the LLM
     * to the {@link Stream}.
     *
     * @param options The {@link Config} object containing the system prompt, user prompt, and other settings.
     * @return A {@link Stream} of characters generated by the model.
     * @throws RuntimeException if the model invocation fails or an error occurs during processing.
     */
    public Stream<String> runAsStream(@Nonnull Config options) {
        BlockingQueueIterator output = new BlockingQueueIterator();
        BlockingQueueIterator error = new BlockingQueueIterator();
        String[] args = buildArgs(options);
        RunAsync.runAsync(getInvoker(args, output, error));
        return BlockingQueueIterator.createStream(output);
    }

    private Runnable getInvoker(String[] args, BlockingQueueIterator output, BlockingQueueIterator error) {
        if (modelType == LLAMA3) {
            return () -> {
                Llama3.STDOUT = QueuingOutputStream.createStream(output.getQueue());
                Llama3.STDERR = QueuingOutputStream.createStream(error.getQueue());
                try {
                    Llama3.main(args);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                } finally {
                    output.setEnd();
                    error.setEnd();
                }
            };
        } else if (modelType == QWEN2) {
            return () -> {
                Qwen2.STDOUT = QueuingOutputStream.createStream(output.getQueue());
                Qwen2.STDERR = QueuingOutputStream.createStream(error.getQueue());
                try {
                    Qwen2.main(args);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                } finally {
                    output.setEnd();
                    error.setEnd();
                }
            };
        }
        throw new IllegalStateException();
    }

    /**
     * Build the arguments that are expected by both Mukel models.
     * @param config Non-null config provided by the user.
     * @return {@link String[]} ready to provide to the Mukel main method(s).
     */
    private String[] buildArgs(@Nonnull Config config) {
        List<String> args = new ArrayList<>();
        args.add("--model");
        args.add(modelPath.toString());
        args.add("--temperature");
        args.add(Float.toString(config.temperature));
        args.add("--instruct");
        if (config.systemPrompt != null) {
            args.add("--system-prompt");
            args.add(config.systemPrompt);
        }
        args.add("--prompt");
        args.add(config.prompt);
        return args.toArray(new String[0]);
    }
}
